### ISSUE TITLE
debian logo

### ISSUE THREAD

**Issue by chainsx** [UMRnInside/RPi-arm64#10]
给你一个debian的logo
![example1](https://assets.ubuntu.com/v1/2eafb62e-openlogo.svg)

**Comment by UMRnInside** [comment]
Roger that :smile: 
But... why do I need it?
This repo intend to be a **debootstrap-based builder**, rather than a **Debian builder**
*******
我拿这个干嘛？
我打算制造一个 **基于debootstrap的构建器** ，而不是 **Debian构建器**
