### ISSUE TITLE
No space left error

### ISSUE THREAD

**Issue by wangwill** [UMRnInside/RPi-arm64#14]
Installing regenerate_ssh_host_keys.service ...
'utils/raspbian_services.files/regenerate_ssh_host_keys.service' -> './utils/../dist/rootfs//lib/systemd/system/regenerate_ssh_host_keys.service'
install: error writing './utils/../dist/rootfs//lib/systemd/system/regenerate_ssh_host_keys.service': No space left on device
Enable regenerate_ssh_host_keys.service ...
Setup Hostname and /etc/hosts ...
/bin/bash: line 0: echo: write error: No space left on device
/bin/bash: line 0: echo: write error: No space left on device
Installing extra packages : 
  rfkill : WiFI controlling...
  avahi-daemon : Aoto Discovery... (default service enabled)
  ntpdate : time keeping (when interface UP)
Reading package lists... Error!
E: Write error - write (28: No space left on device)
E: IO Error saving source cache
E: The package lists or status file could not be parsed or opened.
Reading package lists... Error!
E: Write error - write (28: No space left on device)
E: IO Error saving source cache
E: The package lists or status file could not be parsed or opened.
./utils/install_raspbian_services.sh: line 35: ./utils/../dist/rootfs//etc/sudoers.d/00_pi: No such file or directory
chmod: cannot access './utils/../dist/rootfs//etc/sudoers.d/00_pi': No such file or directory
cp: error writing './utils/../dist/rootfs//etc/RPi-arm64/config': No space left on device
We are at commit 5b6467efdab78ec2235a5a7894fbcc7481b49cbd
./utils/copy_build_info.sh: line 19: echo: write error: No space left on device
Cleanup ...
Unmounting...
Detaching /dev/loop20
Done.

**Comment by wangwill** [comment]
问题开始出现在装locale 后面

磁盘空间有10G以上空余。   生成的img文件1.1G


perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US",
	LC_ALL = (unset),
	LC_PAPER = "zh_CN.UTF-8",
	LC_NUMERIC = "zh_CN.UTF-8",
	LC_IDENTIFICATION = "zh_CN.UTF-8",
	LC_MEASUREMENT = "zh_CN.UTF-8",
	LC_NAME = "zh_CN.UTF-8",
	LC_TELEPHONE = "zh_CN.UTF-8",
	LC_ADDRESS = "zh_CN.UTF-8",
	LC_MONETARY = "zh_CN.UTF-8",
	LC_TIME = "zh_CN.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
/usr/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_MESSAGES to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_ALL to default locale: No such file or directory
Preconfiguring packages ...
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
Selecting previously unselected package libxau6:arm64.

--------------------------------------------------------------------

Selecting previously unselected package openssh-client.
Preparing to unpack .../13-openssh-client_1%3a7.4p1-10+deb9u4_arm64.deb ...
Unpacking openssh-client (1:7.4p1-10+deb9u4) ...
dpkg: error processing archive /tmp/apt-dpkg-install-WGs6PN/13-openssh-client_1%3a7.4p1-10+deb9u4_arm64.deb (--unpack):
 cannot copy extracted data for './usr/bin/ssh' to '/usr/bin/ssh.dpkg-new': failed to write (No space left on device)
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package ucf.
Preparing to unpack .../14-ucf_3.0036_all.deb ...
Moving old data out of the way

-------------------------------------------------------

Installing VideoCore userland(/opt/vc)...
Using hardfp
cp: error writing './stage3/../dist/rootfs//opt/vc/bin/containers_check_frame_int': No space left on device
cp: error writing './stage3/../dist/rootfs//opt/vc/bin/containers_datagram_receiver': No space left on device
cp: error writing './stage3/../dist/rootfs//opt/vc/bin/containers_datagram_sender': No space left on device
cp: error writing './stage3/../dist/rootfs//opt/vc/bin/containers_dump_pktfile': No space left on device
cp: error writing './stage3/../dist/rootfs//opt/vc/bin/containers_rtp_decoder': No space left on device
cp: error writing './stage3/../dist/rootfs//opt/vc/bin/containers_stream_client': No space left on device
cp: error writing './stage3/../dist/rootfs//opt/vc/bin/containers_stream_server': No space left on device
cp: error writing './stage3/../dist/rootfs//opt/vc/bin/containers_test': No space left on device
cp: error writing './stage3/../dist/rootfs//opt/vc/bin/containers_test_bits': No space left on device
cp: error writing './stage3/../dist/rootfs//opt/vc/bin/containers_test_uri': No space left on devic

**Comment by UMRnInside** [comment]
这……
大概是镜像不够大。
解决方法：修改`config`
`IMGSIZE_MB=2048`
********
另外，您使用的是什么配置？`rpi3_defconfig`?
可否把`config`贴上来？

**Comment by wangwill** [comment]
使用的rpi3_defconfig

**Comment by wangwill** [comment]
![image](https://user-images.githubusercontent.com/9379983/49346281-ee3e4b80-f6df-11e8-9358-61e338ff2621.png)
直接git clone repo的 未改defconfig

**Comment by jesset** [comment]
git clone 的时候指定 --depth， 否则有些库类似 rpi-firmware 这样的就会很大

**Comment by wangwill** [comment]
所以是     git clone --depth=1 -b master https://github.com/UMRnInside/RPi-arm64.git  ?

**Comment by wangwill** [comment]
> git clone 的时候指定 --depth， 否则有些库类似 rpi-firmware 这样的就会很大

git clone --depth=1 -b master https://github.com/UMRnInside/RPi-arm64.git

之后编译问题依旧

**Comment by jesset** [comment]
> > git clone 的时候指定 --depth， 否则有些库类似 rpi-firmware 这样的就会很大
> 
> git clone --depth=1 -b master https://github.com/UMRnInside/RPi-arm64.git
> 
> 之后编译问题依旧

不是这个地方，你去看看这里就明白了   https://github.com/UMRnInside/RPi-arm64/blob/master/stage3/bootcode_install.sh#L10

**Comment by jesset** [comment]
> > > git clone 的时候指定 --depth， 否则有些库类似 rpi-firmware 这样的就会很大
> > 
> > 
> > git clone --depth=1 -b master https://github.com/UMRnInside/RPi-arm64.git
> > 之后编译问题依旧
> 
> 不是这个地方，你去看看这里就明白了 https://github.com/UMRnInside/RPi-arm64/blob/master/stage3/bootcode_install.sh#L10

或者你用wget方法，不要用git方法下载

**Comment by UMRnInside** [comment]
@jesset 默认的方法就是wget ......
我正在尝试复现

**Comment by UMRnInside** [comment]
I found the root cause:
firmware-nonfree is TOO LARGE

I have fixed this, and tested it.
********
解决了，firmware-nonfree太大了，只复制子目录足矣。

**Comment by wangwill** [comment]
build 成功   但是中间全程报 /usr/bin/locale 错误 如图

![image](https://user-images.githubusercontent.com/9379983/49386866-6c4a3300-f770-11e8-9cf7-6166ffb19b8b.png)


另外有没有必要把 linux_branch 调为 诸如4.19.y

**Comment by UMRnInside** [comment]
@wangwill locale报错是可接受的，因为这个阶段不需要locale。
不用调整，4.14是长期支持版本
