### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by CodeChikoto** [UMRnInside/RPi-arm64#8]
Fails to autoly resize after boot.
Shutdown gets stuck (Green LED keeps on).
CPU frequency error messages pours out after HostAPD starts (using other adapters).

**Comment by UMRnInside** [comment]
Are you using prebuilt version?
If yes, please tell me the version you are using(e.g. Debian-stretch-btrfs-20180401-PREVIEW)

**Comment by CodeChikoto** [comment]
Not the prebuilt version, I followed the guide and built one myself. RT5372 adapter is used and when a device connects to HostAPD, CPU frequency errors appear, then leading to poweroff failure.

**Comment by UMRnInside** [comment]
You may have encountered some random failures.

We need logs to locate the exace issue(s).

e.g.
```
# Running without docker
mkdir build
bash -x build.sh 2>&1 | tee build/build.log
```

Then put `build/build.log` to gist.

**Comment by UMRnInside** [comment]
Close issue due to lack of activity.
