### ISSUE TITLE
树莓派爱好者基地 系统引用

### ISSUE THREAD

**Issue by YuzukiTsuru** [UMRnInside/RPi-arm64#9]
http://rpifans.cn/pages/imgdown/index.html

**Comment by UMRnInside** [comment]
This is permitted, as they **don't** break LGPLv3
********
好啊！我当然支持啊！

**Comment by UMRnInside** [comment]
提一句……
这是 **Debian** 不是 **Raspbian**

**Comment by YuzukiTsuru** [comment]
Ok，近期修改

**Comment by UMRnInside** [comment]
官方IMG指向了项目地址……
真正的镜像下载地址是：[百度网盘](https://pan.baidu.com/s/1hsZVl1i)
还有，请保留项目地址。

**Comment by UMRnInside** [comment]
加个说明：
> 默认用户名：pi，口令：raspberry
> root口令：raspberry

**Comment by YuzukiTsuru** [comment]
OK👌
